export const insuranceData = [
  {
    company_name: "KAFOLAT SUG‘URTA KOMPANIYASI",
    username: "kafolatuzb",
    followers: 11117,
    following: 0,
    profile_posts_count: 287,
    posts_fetched: 100,
    avg_likes: 27.55,
    avg_comments: 4.73,
    avg_views: 0,
    er_percent: 0.29,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ALSKOM SUG‘URTA KOMPANIYASI",
    username: "alskom.insurance",
    followers: 14852,
    following: 4,
    profile_posts_count: 383,
    posts_fetched: 100,
    avg_likes: 35.26,
    avg_comments: 8.24,
    avg_views: 0,
    er_percent: 0.293,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "APEX INSURANCE",
    username: "apexinsurance.uz",
    followers: 25626,
    following: 8,
    profile_posts_count: 398,
    posts_fetched: 100,
    avg_likes: 904.13,
    avg_comments: 16.18,
    avg_views: 0,
    er_percent: 3.591,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "O‘ZBEKINVEST",
    username: "uzbekinvest_",
    followers: 10340,
    following: 4,
    profile_posts_count: 848,
    posts_fetched: 100,
    avg_likes: 380.39,
    avg_comments: 12.43,
    avg_views: 0,
    er_percent: 3.799,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "SQB INSURANCE",
    username: "sqb.insurance",
    followers: 14733,
    following: 1,
    profile_posts_count: 278,
    posts_fetched: 100,
    avg_likes: 58.68,
    avg_comments: 1.26,
    avg_views: 0,
    er_percent: 0.407,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ASIA INSURANCE",
    username: "asia_insurance.uz",
    followers: 4189,
    following: 14,
    profile_posts_count: 286,
    posts_fetched: 100,
    avg_likes: 9.92,
    avg_comments: 0.49,
    avg_views: 0,
    er_percent: 0.249,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "IMPEX-INSURANCE",
    username: "impex.insurance",
    followers: 9157,
    following: 0,
    profile_posts_count: 363,
    posts_fetched: 100,
    avg_likes: 100.14,
    avg_comments: 2.07,
    avg_views: 0,
    er_percent: 1.116,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "KAFIL-SUG‘URTA",
    username: "kafil_sugurta.uz",
    followers: 6385,
    following: 3,
    profile_posts_count: 445,
    posts_fetched: 100,
    avg_likes: 101.35,
    avg_comments: 4.15,
    avg_views: 0,
    er_percent: 1.652,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "EUROASIA INSURANCE",
    username: "eai.uz",
    followers: 6356,
    following: 1,
    profile_posts_count: 544,
    posts_fetched: 100,
    avg_likes: 82.63,
    avg_comments: 3.09,
    avg_views: 0,
    er_percent: 1.349,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "GROSS SUG‘URTA",
    username: "gross.uzb",
    followers: 4040,
    following: 2,
    profile_posts_count: 508,
    posts_fetched: 100,
    avg_likes: 352.54,
    avg_comments: 5.18,
    avg_views: 0,
    er_percent: 8.854,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "IMKON-SUG‘URTA",
    username: "imkonsugurta.uz",
    followers: 3672,
    following: 1,
    profile_posts_count: 101,
    posts_fetched: 100,
    avg_likes: 13.22,
    avg_comments: 7.32,
    avg_views: 3.01,
    er_percent: 0.559,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "MY-INSURANCE",
    username: "myinsuranceuz",
    followers: 2190,
    following: 1,
    profile_posts_count: 369,
    posts_fetched: 100,
    avg_likes: 39.32,
    avg_comments: 4.29,
    avg_views: 0,
    er_percent: 1.991,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "NEO INSURANCE",
    username: "neoinsurance.uz",
    followers: 3789,
    following: 1,
    profile_posts_count: 244,
    posts_fetched: 100,
    avg_likes: 65.68,
    avg_comments: 3.07,
    avg_views: 0,
    er_percent: 1.814,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "KAPITAL SUG‘URTA",
    username: "kapitalsugurta.uz",
    followers: 2079,
    following: 1,
    profile_posts_count: 429,
    posts_fetched: 100,
    avg_likes: 75.57,
    avg_comments: 8.53,
    avg_views: 0,
    er_percent: 4.045,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "APEX LIFE INSURANCE",
    username: "apexlife.uz",
    followers: 11167,
    following: 7,
    profile_posts_count: 153,
    posts_fetched: 100,
    avg_likes: 316.59,
    avg_comments: 9.2,
    avg_views: 0,
    er_percent: 2.917,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "INSON",
    username: "inson_uzbekistan",
    followers: 2542,
    following: 0,
    profile_posts_count: 477,
    posts_fetched: 100,
    avg_likes: 192.28,
    avg_comments: 4.87,
    avg_views: 0,
    er_percent: 7.756,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "HAMKOR SUG‘URTA",
    username: "hamkorsugurta",
    followers: 1217,
    following: 1,
    profile_posts_count: 245,
    posts_fetched: 100,
    avg_likes: 7.43,
    avg_comments: 0.57,
    avg_views: 0,
    er_percent: 0.657,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ARIA INSURANCE",
    username: "aria_insurance",
    followers: 1170,
    following: 2,
    profile_posts_count: 132,
    posts_fetched: 100,
    avg_likes: 72.24,
    avg_comments: 11.65,
    avg_views: 0,
    er_percent: 7.17,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "GLOBAL INSURANCE GROUP",
    username: "gig.uz",
    followers: 1120,
    following: 0,
    profile_posts_count: 165,
    posts_fetched: 100,
    avg_likes: 49.56,
    avg_comments: 1.27,
    avg_views: 0,
    er_percent: 4.538,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "TRUST-INSURANCE",
    username: "trustinsuranceuz",
    followers: 448,
    following: 0,
    profile_posts_count: 64,
    posts_fetched: 64,
    avg_likes: 8.77,
    avg_comments: 0.61,
    avg_views: 1.52,
    er_percent: 2.093,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ISHONCH SUG‘URTA",
    username: "ishonch_insurance",
    followers: 955,
    following: 0,
    profile_posts_count: 465,
    posts_fetched: 100,
    avg_likes: 0.81,
    avg_comments: 0.14,
    avg_views: 0,
    er_percent: 0.099,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ALFA LIFE INSURANCE",
    username: "alfa.life.uz",
    followers: 990,
    following: 2,
    profile_posts_count: 191,
    posts_fetched: 100,
    avg_likes: 11.49,
    avg_comments: 0.2,
    avg_views: 0,
    er_percent: 1.181,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "O‘ZAGROSUG‘URTA",
    username: "uzagrosugurta",
    followers: 966,
    following: 2,
    profile_posts_count: 519,
    posts_fetched: 100,
    avg_likes: 18.66,
    avg_comments: 1.06,
    avg_views: 0,
    er_percent: 2.041,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ALFA INVEST",
    username: "alfainvest.uz",
    followers: 677,
    following: 1,
    profile_posts_count: 636,
    posts_fetched: 100,
    avg_likes: 49.1,
    avg_comments: 1.89,
    avg_views: 0,
    er_percent: 7.532,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "SEMURG INSURANCE",
    username: "semurgins",
    followers: 402,
    following: 1,
    profile_posts_count: 129,
    posts_fetched: 100,
    avg_likes: 125.49,
    avg_comments: 2.84,
    avg_views: 0,
    er_percent: 31.923,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "TEMIRYO‘L SUG‘URTA",
    username: "tysrasmiy",
    followers: 181,
    following: 3,
    profile_posts_count: 76,
    posts_fetched: 76,
    avg_likes: 34.66,
    avg_comments: 4.22,
    avg_views: 0,
    er_percent: 21.482,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "MOSAIC INSURANCE",
    username: "mosaic_insurance",
    followers: 196,
    following: 30,
    profile_posts_count: 159,
    posts_fetched: 100,
    avg_likes: 12.78,
    avg_comments: 0.21,
    avg_views: 2.33,
    er_percent: 6.628,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "KAFOLAT HAYOT INSURANCE",
    username: "sk_kafolathayot_uz",
    followers: 128,
    following: 34,
    profile_posts_count: 156,
    posts_fetched: 100,
    avg_likes: 1.4,
    avg_comments: 0.02,
    avg_views: 1.36,
    er_percent: 1.109,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "XALQ SUG‘URTA",
    username: "xalqsugurta",
    followers: 129,
    following: 0,
    profile_posts_count: 264,
    posts_fetched: 100,
    avg_likes: 6,
    avg_comments: 0.17,
    avg_views: 0,
    er_percent: 4.783,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "INGO-UZBEKISTON",
    username: "ingo.uzbekistan",
    followers: 91,
    following: 2,
    profile_posts_count: 21,
    posts_fetched: 21,
    avg_likes: 2.71,
    avg_comments: 0,
    avg_views: 0,
    er_percent: 2.983,
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "O‘ZBEKINVEST HAYOT",
    username: "uzbekinvest_hayot",
    followers: 53,
    following: 14,
    profile_posts_count: 19,
    posts_fetched: 19,
    avg_likes: 10.79,
    avg_comments: 0.26,
    avg_views: 0,
    er_percent: 20.854,
    last_updated_date: "1/2/2026",
  },
];
